CREATE TABLE IF NOT EXISTS estimate_template_rows (
    template_row_id TEXT PRIMARY KEY,
    document_id TEXT NOT NULL,
    job_id TEXT,
    source_file TEXT,
    template_type TEXT,
    sheet_name TEXT,
    row_number INTEGER,
    cell_range TEXT,
    template_bucket TEXT,
    template_section TEXT,
    line_item_kind TEXT,
    row_label TEXT,
    raw_text TEXT,
    cell_values JSONB,
    formula_cells JSONB,
    selected_item_name TEXT,
    quantity NUMERIC,
    unit TEXT,
    unit_price NUMERIC,
    estimated_units NUMERIC,
    estimated_cost NUMERIC,
    days NUMERIC,
    crew_size NUMERIC,
    total_hours NUMERIC,
    daily_rate NUMERIC,
    trips NUMERIC,
    round_trip_miles NUMERIC,
    cost_per_mile NUMERIC,
    warranty_years NUMERIC,
    overhead_pct NUMERIC,
    profit_pct NUMERIC,
    parsed_confidence NUMERIC,
    needs_review BOOLEAN DEFAULT FALSE,
    parser_version TEXT,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE estimate_template_rows
    ADD COLUMN IF NOT EXISTS job_id TEXT,
    ADD COLUMN IF NOT EXISTS source_file TEXT,
    ADD COLUMN IF NOT EXISTS template_type TEXT,
    ADD COLUMN IF NOT EXISTS sheet_name TEXT,
    ADD COLUMN IF NOT EXISTS row_number INTEGER,
    ADD COLUMN IF NOT EXISTS cell_range TEXT,
    ADD COLUMN IF NOT EXISTS template_bucket TEXT,
    ADD COLUMN IF NOT EXISTS template_section TEXT,
    ADD COLUMN IF NOT EXISTS line_item_kind TEXT,
    ADD COLUMN IF NOT EXISTS row_label TEXT,
    ADD COLUMN IF NOT EXISTS raw_text TEXT,
    ADD COLUMN IF NOT EXISTS cell_values JSONB,
    ADD COLUMN IF NOT EXISTS formula_cells JSONB,
    ADD COLUMN IF NOT EXISTS selected_item_name TEXT,
    ADD COLUMN IF NOT EXISTS quantity NUMERIC,
    ADD COLUMN IF NOT EXISTS unit TEXT,
    ADD COLUMN IF NOT EXISTS unit_price NUMERIC,
    ADD COLUMN IF NOT EXISTS estimated_units NUMERIC,
    ADD COLUMN IF NOT EXISTS estimated_cost NUMERIC,
    ADD COLUMN IF NOT EXISTS selector_code NUMERIC,
    ADD COLUMN IF NOT EXISTS resolved_item_name TEXT,
    ADD COLUMN IF NOT EXISTS area_sqft NUMERIC,
    ADD COLUMN IF NOT EXISTS thickness_inches NUMERIC,
    ADD COLUMN IF NOT EXISTS yield_or_coverage NUMERIC,
    ADD COLUMN IF NOT EXISTS yield_factor NUMERIC,
    ADD COLUMN IF NOT EXISTS estimated_sets NUMERIC,
    ADD COLUMN IF NOT EXISTS foam_brand TEXT,
    ADD COLUMN IF NOT EXISTS foam_density_lb NUMERIC,
    ADD COLUMN IF NOT EXISTS units_per_sqft_per_inch NUMERIC,
    ADD COLUMN IF NOT EXISTS sets_per_sqft_per_inch NUMERIC,
    ADD COLUMN IF NOT EXISTS cost_per_sqft_per_inch NUMERIC,
    ADD COLUMN IF NOT EXISTS gal_per_100_sqft NUMERIC,
    ADD COLUMN IF NOT EXISTS gal_per_sqft NUMERIC,
    ADD COLUMN IF NOT EXISTS estimated_gallons NUMERIC,
    ADD COLUMN IF NOT EXISTS linear_ft NUMERIC,
    ADD COLUMN IF NOT EXISTS ft_per_unit NUMERIC,
    ADD COLUMN IF NOT EXISTS margin_pct NUMERIC,
    ADD COLUMN IF NOT EXISTS waste_margin_cell TEXT,
    ADD COLUMN IF NOT EXISTS quantity_cell_role TEXT,
    ADD COLUMN IF NOT EXISTS formula_model TEXT,
    ADD COLUMN IF NOT EXISTS days NUMERIC,
    ADD COLUMN IF NOT EXISTS crew_size NUMERIC,
    ADD COLUMN IF NOT EXISTS total_hours NUMERIC,
    ADD COLUMN IF NOT EXISTS daily_rate NUMERIC,
    ADD COLUMN IF NOT EXISTS crew_selector_code NUMERIC,
    ADD COLUMN IF NOT EXISTS hourly_rate NUMERIC,
    ADD COLUMN IF NOT EXISTS calculated_cost NUMERIC,
    ADD COLUMN IF NOT EXISTS formula_mode TEXT,
    ADD COLUMN IF NOT EXISTS trips NUMERIC,
    ADD COLUMN IF NOT EXISTS round_trip_miles NUMERIC,
    ADD COLUMN IF NOT EXISTS cost_per_mile NUMERIC,
    ADD COLUMN IF NOT EXISTS warranty_years NUMERIC,
    ADD COLUMN IF NOT EXISTS overhead_pct NUMERIC,
    ADD COLUMN IF NOT EXISTS profit_pct NUMERIC,
    ADD COLUMN IF NOT EXISTS parsed_confidence NUMERIC,
    ADD COLUMN IF NOT EXISTS needs_review BOOLEAN DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS parser_version TEXT,
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT now(),
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT now();

CREATE INDEX IF NOT EXISTS idx_estimate_template_rows_document_id ON estimate_template_rows(document_id);
CREATE INDEX IF NOT EXISTS idx_estimate_template_rows_job_id ON estimate_template_rows(job_id);
CREATE INDEX IF NOT EXISTS idx_estimate_template_rows_sheet_row ON estimate_template_rows(sheet_name, row_number);
CREATE INDEX IF NOT EXISTS idx_estimate_template_rows_template_bucket ON estimate_template_rows(template_bucket);
CREATE INDEX IF NOT EXISTS idx_estimate_template_rows_template_type ON estimate_template_rows(template_type);
CREATE INDEX IF NOT EXISTS idx_estimate_template_rows_line_item_kind ON estimate_template_rows(line_item_kind);
CREATE INDEX IF NOT EXISTS idx_estimate_template_rows_needs_review ON estimate_template_rows(needs_review);
