[server]
maxUploadSize = 2048
fileWatcherType = "none"
enableStaticServing = true

[[theme.fontFaces]]
family = "SpaceGrotesk"
url = "app/static/SpaceGrotesk-VariableFont_wght.ttf"

[[theme.fontFaces]]
family = "SpaceMono"
url = "app/static/SpaceMono-Bold.ttf"
style = "normal"
weight = 700

[[theme.fontFaces]]
family = "SpaceMono"
url = "app/static/SpaceMono-BoldItalic.ttf"
style = "italic"
weight = 700

[[theme.fontFaces]]
family = "SpaceMono"
url = "app/static/SpaceMono-Italic.ttf"
style = "italic"
weight = 400

[[theme.fontFaces]]
family = "SpaceMono"
url = "app/static/SpaceMono-Regular.ttf"
style = "normal"
weight = 400

[theme]
base = "light"
primaryColor = "#cb785c"
backgroundColor = "#fdfdf8"
secondaryBackgroundColor = "#ecebe3"
textColor = "#3d3a2a"
linkColor = "#3d3a2a"
borderColor = "#d3d2ca"
showWidgetBorder = true
baseRadius = "0.75rem"
buttonRadius = "full"
font = "SpaceGrotesk"
headingFontWeights = [600, 500, 500, 500, 500, 500]
headingFontSizes = ["3rem", "2rem"]
codeFont = "SpaceMono"
codeFontSize = ".75rem"
codeBackgroundColor = "#ecebe4"
showSidebarBorder = true
chartCategoricalColors = ["#52718C", "#5E8F63", "#B88929", "#CB785C", "#8B6F9E", "#C65F4C", "#4F8F8A", "#9A7B4F", "#6F6A58", "#A85F7A"]

[theme.sidebar]
backgroundColor = "#f0f0ec"
secondaryBackgroundColor = "#ecebe3"
headingFontSizes = ["1.6rem", "1.4rem", "1.2rem"]
dataframeHeaderBackgroundColor = "#e4e4e0"
